version: '3.6'
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cqrs
  mongodb:
    image: mongo
    restart: always